name: amarbabu_portfolio
description: "Portfolio of Amarbabu T – Flutter developer with experience in building cross-platform mobile and web apps using Flutter, Firebase, Riverpod, Stripe, and more."

publish_to: 'none' # Prevent accidental publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.1
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  url_launcher: ^6.3.1
  flutter_animate: ^4.5.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/docs/

  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/source_code/SourceCodePro-Black.ttf
        - asset: assets/fonts/source_code/SourceCodePro-Bold.ttf
          weight: 700
        - asset: assets/fonts/source_code/SourceCodePro-Light.ttf
          weight: 300
        - asset: assets/fonts/source_code/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/source_code/SourceCodePro-Italic.ttf
          style: italic
